apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-02-18T08:31:39Z"
  generation: 1
  labels:
    run: nginx
  name: nginx-new
  namespace: default
  resourceVersion: "29870"
  uid: 640c56f9-364c-4d48-bf39-2f4f04e6e3a6
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
