apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::717188664763:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-YwPGqRttARXx
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::717188664763:user/ramu
      username: ramu
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::717188664763:user/chelloju
      username: chelloju
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T12:35:53Z"
  name: aws-auth
  namespace: kube-system
  uid: dc6c6ce9-d785-4a3b-83c3-69246515488a
