apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

# New Standard Syntax
labels:
  - pairs:
      env: dev
      project: roboshop
    includeSelectors: true